#!/usr/bin/env python3
"""Generate a Home Assistant package for a SONOFF water valve schedule."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


VALID_WEEKDAYS = {"mon", "tue", "wed", "thu", "fri", "sat", "sun"}
TIME_PATTERN = re.compile(r"^\d{2}:\d{2}(:\d{2})?$")


def slugify(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip().lower())
    value = re.sub(r"_+", "_", value).strip("_")
    if not value:
        raise ValueError("Schedule names must contain at least one letter or number.")
    return value


def ensure_time(value: str) -> str:
    if not TIME_PATTERN.match(value):
        raise ValueError(f"Invalid time '{value}'. Use HH:MM or HH:MM:SS.")
    return value if value.count(":") == 2 else f"{value}:00"


def validate_schedule(schedule: dict) -> dict:
    if not schedule.get("enabled", True):
        return {}

    name = str(schedule["name"]).strip()
    run_time = ensure_time(str(schedule["time"]).strip())
    duration_minutes = int(schedule["duration_minutes"])
    if duration_minutes <= 0:
        raise ValueError(f"Schedule '{name}' must use a positive duration.")

    weekdays = schedule.get("weekdays")
    if weekdays:
        weekdays = [str(day).lower() for day in weekdays]
        invalid = [day for day in weekdays if day not in VALID_WEEKDAYS]
        if invalid:
            raise ValueError(
                f"Schedule '{name}' uses invalid weekdays: {', '.join(invalid)}."
            )

    return {
        "name": name,
        "slug": slugify(name),
        "time": run_time,
        "duration_minutes": duration_minutes,
        "weekdays": weekdays,
    }


def make_automation_lines(entity_id: str, config: dict, schedule: dict) -> list[str]:
    domain = entity_id.split(".", 1)[0]
    automation_id = f"{config['automation_id_prefix']}_{schedule['slug']}"
    alias = f"{config['alias_prefix']} - {schedule['name']}"
    description = (
        f"Turns {entity_id} on at {schedule['time']} for "
        f"{schedule['duration_minutes']} minute(s)."
    )

    lines = [
        "  - id: " + json.dumps(automation_id),
        "    alias: " + json.dumps(alias),
        "    description: " + json.dumps(description),
        "    mode: single",
        "    triggers:",
        "      - trigger: time",
        "        at: " + json.dumps(schedule["time"]),
    ]

    if schedule["weekdays"]:
        lines.extend(
            [
                "    conditions:",
                "      - condition: time",
                "        weekday:",
            ]
        )
        for day in schedule["weekdays"]:
            lines.append("          - " + day)
    else:
        lines.append("    conditions: []")

    lines.extend(
        [
            "    actions:",
            f"      - action: {domain}.turn_on",
            "        target:",
            "          entity_id: " + entity_id,
            "      - delay:",
            "          minutes: " + str(schedule["duration_minutes"]),
            f"      - action: {domain}.turn_off",
            "        target:",
            "          entity_id: " + entity_id,
        ]
    )
    return lines


def render_package(config: dict) -> str:
    entity_id = str(config["entity_id"]).strip()
    schedules = [
        validate_schedule(schedule)
        for schedule in config.get("schedules", [])
    ]
    schedules = [schedule for schedule in schedules if schedule]
    if not schedules:
        raise ValueError("No enabled schedules were found in the input file.")

    timezone = config.get("timezone", "unspecified")
    lines = [
        "# Generated by home-assistant-sonoff-water-valve",
        f"# Operator timezone: {timezone}",
        "# Home Assistant runs these automations in Home Assistant's configured timezone.",
        "automation:",
    ]

    for schedule in schedules:
        lines.extend(make_automation_lines(entity_id, config, schedule))

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="Path to the schedule JSON file.")
    parser.add_argument("--output", required=True, help="Path to the generated YAML package.")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    with input_path.open("r", encoding="utf-8") as handle:
        config = json.load(handle)

    required_keys = {"automation_id_prefix", "alias_prefix", "entity_id", "schedules"}
    missing = sorted(required_keys - set(config))
    if missing:
        raise ValueError("Missing required keys: " + ", ".join(missing))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_package(config), encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
